import { getParam } from './params';
import { putGroupConfig, type GroupConfig } from './store';

/** 起票・コメントの末尾に必ず付ける表記 */
export const FOOTER = '\n\n---\nGenerated by AWS Bedrock (Grok 4.6)';
/** ミラー記録の末尾に付ける表記（Grokは介していないため別表記） */
export const MIRROR_FOOTER = '\n\n---\nMirrored from LINE';

async function call(
  cfg: GroupConfig,
  path: string,
  init?: { method?: string; body?: Record<string, string> },
) {
  const apiKey = await getParam(`groups/${cfg.groupId}/backlog-api-key`);
  const res = await fetch(
    `${cfg.spaceUrl.replace(/\/$/, '')}/api/v2${path}`,
    {
      method: init?.method ?? 'GET',
      headers: {
        'Backlog-API-Key': apiKey,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: init?.body ? new URLSearchParams(init.body) : undefined,
    },
  );
  if (!res.ok) {
    throw new Error(`Backlog ${path}: ${res.status} ${await res.text()}`);
  }
  return res.json() as Promise<Record<string, any>>;
}

/** projectKey → projectId を解決して設定にキャッシュ */
export async function resolveProjectId(cfg: GroupConfig): Promise<number> {
  if (cfg.projectId) return cfg.projectId;
  const p = await call(
    cfg,
    `/projects/${encodeURIComponent(cfg.projectKey)}`,
  );
  cfg.projectId = p.id as number;
  await putGroupConfig(cfg);
  return p.id as number;
}

/** APIキー所有者（自分のコメントが通知ループしないよう判定に使う） */
export async function getMyself(
  cfg: GroupConfig,
): Promise<{ id: number; name: string }> {
  if (cfg.botBacklogUserId) {
    return { id: cfg.botBacklogUserId, name: '' };
  }
  const me = await call(cfg, '/users/myself');
  cfg.botBacklogUserId = me.id as number;
  await putGroupConfig(cfg);
  return { id: me.id as number, name: me.name as string };
}

export interface IssueInput {
  summary: string;
  description: string;
  dueDate?: string | null;
  issueTypeId?: number;
  priorityId?: number;
  assigneeId?: number;
}

export async function createIssue(cfg: GroupConfig, d: IssueInput) {
  const projectId = await resolveProjectId(cfg);
  const issueTypeId = d.issueTypeId ?? cfg.issueTypeId;
  if (!issueTypeId) throw new Error('issueTypeId が未設定です');
  const body: Record<string, string> = {
    projectId: String(projectId),
    summary: d.summary,
    description: d.description + FOOTER,
    issueTypeId: String(issueTypeId),
    priorityId: String(d.priorityId ?? cfg.priorityId ?? 3),
  };
  const assigneeId = d.assigneeId ?? cfg.assigneeId;
  if (assigneeId) body.assigneeId = String(assigneeId);
  if (d.dueDate) body.dueDate = d.dueDate;
  return call(cfg, '/issues', { method: 'POST', body });
}

export async function addComment(
  cfg: GroupConfig,
  issueKey: string,
  content: string,
  opts?: { notifiedUserIds?: number[]; footer?: string },
) {
  const body: Record<string, string> = {
    content: content + (opts?.footer ?? FOOTER),
  };
  opts?.notifiedUserIds?.forEach((id, i) => {
    body[`notifiedUserId[${i}]`] = String(id);
  });
  return call(cfg, `/issues/${encodeURIComponent(issueKey)}/comments`, {
    method: 'POST',
    body,
  });
}

// ---- 管理画面の選択肢用メタ情報 ----
export const listIssueTypes = async (cfg: GroupConfig) =>
  call(cfg, `/projects/${await resolveProjectId(cfg)}/issueTypes`);
export const listPriorities = (cfg: GroupConfig) => call(cfg, '/priorities');
export const listProjectUsers = async (cfg: GroupConfig) =>
  call(cfg, `/projects/${await resolveProjectId(cfg)}/users`);
